image: 
  file: .gitpod.Containerfile

tasks:
  - init: echo 'Initializing project'
    command: echo 'Starting project'

ports:
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - redhat.vscode-yaml
    - redhat.vscode-xml
    - redhat.java
    - redhat.vscode-quarkus
    - redhat.vscode-microprofile
    - ms-azuretools.vscode-docker
    - ms-python.python
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - enkia.tokyo-night
