# Generated by Django 5.0.4 on 2024-04-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transx_new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='spoken_language',
            field=models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('PT', 'Portuguese')], default='EN', max_length=50),
        ),
    ]
